package com.healthcare.home.auth;

public enum Access {
    ADD_STAFF,
    UPDATE_STAFF,
    VIEW_RESIDENT,
    WRITE_PRESCRIPTION,
    ADMINISTER_MEDICATION,
    ADD_RESIDENT,
    MOVE_RESIDENT,
    SHIFT_ASSIGNMENT,
    UPDATE_PRESCRIPTION,
    DISCHARGE_RESIDENT
}
